// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClZGEPQTntFl7txmUKepdffNqFssS77OI',
    appId: '1:783941719007:web:53e12d984aef50ca51aa6a',
    messagingSenderId: '783941719007',
    projectId: 'notesapp-9db02',
    authDomain: 'notesapp-9db02.firebaseapp.com',
    storageBucket: 'notesapp-9db02.firebasestorage.app',
    measurementId: 'G-9WJX5GTQRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOduVpH7OVYn1-bRY9JDdsuE7aHLFBnBI',
    appId: '1:783941719007:android:006de68c20c61b7951aa6a',
    messagingSenderId: '783941719007',
    projectId: 'notesapp-9db02',
    storageBucket: 'notesapp-9db02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfWGUQe1DkrI8mXVjli8S_JVyUGPAGnA8',
    appId: '1:783941719007:ios:34e8347b826d5c3351aa6a',
    messagingSenderId: '783941719007',
    projectId: 'notesapp-9db02',
    storageBucket: 'notesapp-9db02.firebasestorage.app',
    iosBundleId: 'com.example.notesFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfWGUQe1DkrI8mXVjli8S_JVyUGPAGnA8',
    appId: '1:783941719007:ios:34e8347b826d5c3351aa6a',
    messagingSenderId: '783941719007',
    projectId: 'notesapp-9db02',
    storageBucket: 'notesapp-9db02.firebasestorage.app',
    iosBundleId: 'com.example.notesFirebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClZGEPQTntFl7txmUKepdffNqFssS77OI',
    appId: '1:783941719007:web:355ecaa2526548dd51aa6a',
    messagingSenderId: '783941719007',
    projectId: 'notesapp-9db02',
    authDomain: 'notesapp-9db02.firebaseapp.com',
    storageBucket: 'notesapp-9db02.firebasestorage.app',
    measurementId: 'G-03FG4H5ZZB',
  );

}